---
- name: Configure lograte for custom-monitor service 
  hosts: all
  become: true

  tasks:
  # Check logrotate service status
  - name: Get Logrotate Status
    ansible.builtin.systemd:
      name: logrotate
    register: logrotate_info
    tags: 
      - never

  # Print logrotate service status
  - debug: 
      var: logrotate_info.status.ActiveState
    tags: 
      - never

  # Fails the playbook if log directory for custom-monitor over 500mb
  - name: Fail playbook if log directory over 500mb
    ansible.builtin.command:  du -h /var/log/custom-monitor | awk '{print $1}'
    register: directory_size
    when: dry_run
    failed_when: directory_size >= 500

  # Print list of log files older than 30 days
  - name: Return list of log files ending in .gz extention older than 30 days
    ansible.builtin.command: find /var/log/custom-monitor/ -mtime +30 -print
    become: true
    register: prune_result
    tags: 
      - prune
    when: dry_run

  # Remove log files older than 30 days
  - name: Removes log files ending in .gz extention older than 30 days
    ansible.builtin.command: find /var/log/custom-monitor/ -mtime +30 -exec rm -f {} +
    become: true
    register: prune_result
    tags: 
      - prune
    when: dry_run == False

  - debug: 
      var: prune_result
    tags: 
      - prune

  # Ensure /var/log/custom-monitor/ exists and has correct permissions
  - name: Ensure log directory exists and permissions
    ansible.builtin.file:
      path: /var/log/custom-monitor/
      state: directory
      mode: '0755'
    tags: 
      - verify

  # Deploy logrotate configuration file for /var/log/custom-monitor/*.log
  - name: Deploy configuration file 
    ansible.builtin.copy:
      src: logrotate-configs/custom-monitor
      dest: /etc/logrotate.d/custom-monitor
      owner: root
      group: root
      mode: '0644'
    tags: 
      - deploy
