---
- name: Configure lograte for custom-monitor service 
  hosts: all
  become: true

  tasks:
  # Ensure /var/log/custom-monitor/ exists and has correct permissions
  - name: Ensure log directory exists and permissions
    ansible.builtin.file:
      path: /var/log/custom-monitor/
      state: directory
      mode: '0755'
    tags: 
      - verify

  - name: Check /etc/logrotate.d/ directory
    ansible.builtin.command: ls -a /etc/logrotate.d/
    tags: 
      - verify

  # Deploy logrotate configuration for /var/log/custom-monitor/*.log
  - name: Deploy configuration file 
    ansible.builtin.template:
      src: custom-monitor.d
      dest: /etc/logrotate.d/custom-monitor
      owner: root
      group: root
      mode: '0644'
    tags: 
      - deploy

