---
- name: Configure lograte for custom-monitor service 
  hosts: all
  become: true

  tasks:
  # Check logrotate service status
  - name: Get Logrotate Status
    ansible.builtin.systemd:
      name: logrotate
    register: logrotate_info
    tags: 
      - never

  # Print logrotate service status
  - debug: 
      var: logrotate_info.status.ActiveState
    tags: 
      - never

  # Ensure /var/log/custom-monitor/ exists and has correct permissions
  - name: Ensure log directory exists and permissions
    ansible.builtin.file:
      path: /var/log/custom-monitor/
      state: directory
      mode: '0755'
    tags: 
      - verify

  # Deploy logrotate configuration file for /var/log/custom-monitor/*.log
  - name: Deploy configuration file 
    ansible.builtin.copy:
      src: logrotate-configs/custom-monitor
      dest: /etc/logrotate.d/custom-monitor
      owner: root
      group: root
      mode: '0644'
    tags: 
      - deploy

